### ISSUE TITLE
Orchard v1.9.1

### ISSUE THREAD

**Issue by loshuliveros** [urbanit/OrchardCMS.Localization-Extensions#2]
After upgrading Orchard to version 1.9.1 localization of categories stopped working (Step 7 from Example 2). I'm able create translation of Taxonomy terms, but they aren't visible in any translated taxonomies. Only category of default language is visible in taxonomy in the same language.

**Comment by Piedone** [comment]
Can you take a look whether there is anything in the logs? I don't know what related changed in 1.9.1 but apparently something became incompatible.

**Comment by loshuliveros** [comment]
i use datwendoo.localization for switching languages, but it worked in 1.9.0... here is piece from log:

2015-07-09 14:46:02,264 [32] Orchard.ContentManagement.Drivers.Coordinators.ContentPartDriverCoordinator - Default - NullReferenceException thrown from IContentPartDriver by Datwendo.Localization.Drivers.LocalizationPartDriver
System.NullReferenceException: Object reference not set to an instance of an object.
   at Orchard.Localization.Handlers.LocalizationPartHandler.<>c__DisplayClass7_0.<PropertySetHandlers>b__0(CultureRecord cultureRecord)
   at Orchard.ContentManagement.Utilities.LazyField`1.SetValue(T value) in XYZ\src\Orchard\ContentManagement\Utilities\LazyField.cs:line 33
   at Orchard.ContentManagement.Utilities.LazyField`1.set_Value(T value) in XYZ\src\Orchard\ContentManagement\Utilities\LazyField.cs:line 11
   at Orchard.Localization.Models.LocalizationPart.set_Culture(CultureRecord value)
   at Orchard.Localization.Services.LocalizationService.Orchard.Localization.Services.ILocalizationService.SetContentCulture(IContent content, String culture)
   at Datwendo.Localization.Drivers.LocalizationPartDriver.Editor(LocalizationPart part, IUpdateModel updater, Object shapeHelper)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute4[T0,T1,T2,T3,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
   at Orchard.ContentManagement.Drivers.ContentPartDriver`1.Orchard.ContentManagement.Drivers.IContentPartDriver.UpdateEditor(UpdateEditorContext context) in XYZ\src\Orchard\ContentManagement\Drivers\ContentPartDriver.cs:line 90
   at Orchard.ContentManagement.Drivers.Coordinators.ContentPartDriverCoordinator.<>c__DisplayClass11_0.<UpdateEditor>b__0(IContentPartDriver driver) in XYZ\src\Orchard\ContentManagement\Drivers\Coordinators\ContentPartDriverCoordinator.cs:line 63
   at Orchard.InvokeExtensions.Invoke[TEvents](IEnumerable`1 events, Action`1 dispatch, ILogger logger) in XYZ\src\Orchard\InvokeExtensions.cs:line 17
2015-07-09 14:46:49,726 [18] Orchard.ContentManagement.Drivers.Coordinators.ContentPartDriverCoordinator - Default - NullReferenceException thrown from IContentPartDriver by Datwendo.Localization.Drivers.LocalizationPartDriver
System.NullReferenceException: Object reference not set to an instance of an object.
   at Orchard.Localization.Handlers.LocalizationPartHandler.<>c__DisplayClass7_0.<PropertySetHandlers>b__0(CultureRecord cultureRecord)
   at Orchard.ContentManagement.Utilities.LazyField`1.SetValue(T value) in XYZ\src\Orchard\ContentManagement\Utilities\LazyField.cs:line 33
   at Orchard.ContentManagement.Utilities.LazyField`1.set_Value(T value) in XYZ\src\Orchard\ContentManagement\Utilities\LazyField.cs:line 11
   at Orchard.Localization.Models.LocalizationPart.set_Culture(CultureRecord value)
   at Orchard.Localization.Services.LocalizationService.Orchard.Localization.Services.ILocalizationService.SetContentCulture(IContent content, String culture)
   at Datwendo.Localization.Drivers.LocalizationPartDriver.Editor(LocalizationPart part, IUpdateModel updater, Object shapeHelper)
   at Orchard.ContentManagement.Drivers.ContentPartDriver`1.Orchard.ContentManagement.Drivers.IContentPartDriver.UpdateEditor(UpdateEditorContext context) in XYZ\src\Orchard\ContentManagement\Drivers\ContentPartDriver.cs:line 90
   at Orchard.ContentManagement.Drivers.Coordinators.ContentPartDriverCoordinator.<>c__DisplayClass11_0.<UpdateEditor>b__0(IContentPartDriver driver) in XYZ\src\Orchard\ContentManagement\Drivers\Coordinators\ContentPartDriverCoordinator.cs:line 63
   at Orchard.InvokeExtensions.Invoke[TEvents](IEnumerable`1 events, Action`1 dispatch, ILogger logger) in XYZ\src\Orchard\InvokeExtensions.cs:line 17

**Comment by urbanit** [comment]
If I am not wrong, there is an inbuild culture picker in 1.9.x. Please try this.

**Comment by loshuliveros** [comment]
Thanks, there is, but when i enable this module, it injects navigation in every content and widgets: "Translation: en-US sk-SK"... Can i disable it somewhere or should i override some template? Maybe it is good feature for authenticated admin or editor, but not anonymous...

Anyway, now i tested scenario for adding taxonomy category and it works fine without Datwendoo...

Now i need remove all menus "Translation" and place language picker on topbar and style it with flags. Could you navigate me for some help how to do it?

**Comment by loshuliveros** [comment]
I'm sorry, my mistake, it's Datwendoo issue, i'm closing it...
